In [ ]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = 'https://raw.githubusercontent.com/umangkejriwal1122/Machine-Learning/master/Data%20Sets/titanic.csv'
print(path)

https://raw.githubusercontent.com/umangkejriwal1122/Machine-Learning/master/Data%20Sets/titanic.csv


In [ ]:
# Importing the dataset from Google Drive
dataset = pd.read_csv(path)

In [ ]:
print(dataset)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]


In [ ]:
#Print Total number of Rows & columns in dataset
print(dataset.shape)

(891, 12)


In [ ]:
#Print Imformation about data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
# Data type information
types = dataset.dtypes
print(types)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [ ]:
#Count total number of rank in Data
class_counts = dataset.groupby('Pclass').size()
print(class_counts)

Pclass
1    216
2    184
3    491
dtype: int64


In [ ]:

#Count total number of rank in Data
class_counts = dataset.groupby('SibSp').size()
print(class_counts)

SibSp
0    608
1    209
2     28
3     16
4     18
5      5
8      7
dtype: int64


In [ ]:


#Count total number of rank in Data
class_counts = dataset.groupby('Parch').size()
print(class_counts)

Parch
0    678
1    118
2     80
3      5
4      4
5      5
6      1
dtype: int64


In [ ]:

#Count total number of rank in Data
class_counts = dataset.groupby('Ticket').size()
print(class_counts)

Ticket
110152         3
110413         3
110465         2
110564         1
110813         1
              ..
W./C. 6608     4
W./C. 6609     1
W.E.P. 5734    1
W/C 14208      1
WE/P 5735      2
Length: 681, dtype: int64


In [ ]:
X=dataset[["Age","SibSp","Parch","Fare","Sex","Pclass"]]
y=dataset["Survived"]

In [ ]:
print(X)

      Age  SibSp  Parch     Fare     Sex  Pclass
0    22.0      1      0   7.2500    male       3
1    38.0      1      0  71.2833  female       1
2    26.0      0      0   7.9250  female       3
3    35.0      1      0  53.1000  female       1
4    35.0      0      0   8.0500    male       3
..    ...    ...    ...      ...     ...     ...
886  27.0      0      0  13.0000    male       2
887  19.0      0      0  30.0000  female       1
888   NaN      1      2  23.4500  female       3
889  26.0      0      0  30.0000    male       1
890  32.0      0      0   7.7500    male       3

[891 rows x 6 columns]


In [ ]:
print(y)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64


In [ ]:
X.isnull().sum()

Age       177
SibSp       0
Parch       0
Fare        0
Sex         0
Pclass      0
dtype: int64

In [ ]:
y.isnull().sum()

0

In [ ]:
mean_age=X['Age'].mean()
mean_age=np.round(mean_age,2)
mean_age

29.7

In [ ]:
X['Age'].fillna(mean_age,inplace=True)
X.head(20)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


Age  SibSp  Parch     Fare     Sex  Pclass
0   22.0      1      0   7.2500    male       3
1   38.0      1      0  71.2833  female       1
2   26.0      0      0   7.9250  female       3
3   35.0      1      0  53.1000  female       1
4   35.0      0      0   8.0500    male       3
5   29.7      0      0   8.4583    male       3
6   54.0      0      0  51.8625    male       1
7    2.0      3      1  21.0750    male       3
8   27.0      0      2  11.1333  female       3
9   14.0      1      0  30.0708  female       2
10   4.0      1      1  16.7000  female       3
11  58.0      0      0  26.5500  female       1
12  20.0      0      0   8.0500    male       3
13  39.0      1      5  31.2750    male       3
14  14.0      0      0   7.8542  female       3
15  55.0      0      0  16.0000  female       2
16   2.0      4      1  29.1250    male       3
17  29.7      0      0  13.0000    male       2
18  31.0      1      0  18.0000  female       3
19  29.7      0      0   7.2250  female       3

In [ ]:
X.isnull().sum()

Age       0
SibSp     0
Parch     0
Fare      0
Sex       0
Pclass    0
dtype: int64

In [ ]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X["Sex"] = labelencoder_X.fit_transform(X["Sex"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [ ]:
print(X)

      Age  SibSp  Parch     Fare  Sex  Pclass
0    22.0      1      0   7.2500    1       3
1    38.0      1      0  71.2833    0       1
2    26.0      0      0   7.9250    0       3
3    35.0      1      0  53.1000    0       1
4    35.0      0      0   8.0500    1       3
..    ...    ...    ...      ...  ...     ...
886  27.0      0      0  13.0000    1       2
887  19.0      0      0  30.0000    0       1
888  29.7      1      2  23.4500    0       3
889  26.0      0      0  30.0000    1       1
890  32.0      0      0   7.7500    1       3

[891 rows x 6 columns]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [ ]:
print(X_train)

      Age  SibSp  Parch     Fare  Sex  Pclass
105  28.0      0      0   7.8958    1       3
68   17.0      4      2   7.9250    0       3
253  30.0      1      0  16.1000    1       3
320  22.0      0      0   7.2500    1       3
706  45.0      0      0  13.5000    0       2
..    ...    ...    ...      ...  ...     ...
835  39.0      1      1  83.1583    0       1
192  19.0      1      0   7.8542    0       3
629  29.7      0      0   7.7333    1       3
559  36.0      1      0  17.4000    0       3
684  60.0      1      1  39.0000    1       2

[668 rows x 6 columns]


In [ ]:
print(X_test)

      Age  SibSp  Parch      Fare  Sex  Pclass
495  29.7      0      0   14.4583    1       3
648  29.7      0      0    7.5500    1       3
278   7.0      4      1   29.1250    1       3
31   29.7      1      0  146.5208    0       1
255  29.0      0      2   15.2458    0       3
..    ...    ...    ...       ...  ...     ...
167  45.0      1      4   27.9000    0       3
306  29.7      0      0  110.8833    0       1
379  19.0      0      0    7.7750    1       3
742  21.0      2      2  262.3750    0       1
10    4.0      1      1   16.7000    0       3

[223 rows x 6 columns]


In [ ]:
print(y_test)

495    0
648    0
278    0
31     1
255    1
      ..
167    0
306    1
379    0
742    1
10     1
Name: Survived, Length: 223, dtype: int64


In [ ]:
print(y_train)

105    0
68     1
253    0
320    0
706    1
      ..
835    1
192    1
629    0
559    1
684    0
Name: Survived, Length: 668, dtype: int64


In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-0.14360052 -0.46037161 -0.47720996 -0.48380773  0.72705166  0.83012938]
 [-0.99276889  2.98532288  1.95619654 -0.48323058 -1.37541808  0.83012938]
 [ 0.01079373  0.40105202 -0.47720996 -0.32165051  0.72705166  0.83012938]
 ...
 [-0.01236541 -0.46037161 -0.47720996 -0.48701956  0.72705166  0.83012938]
 [ 0.47397648  0.40105202 -0.47720996 -0.29595582 -1.37541808  0.83012938]
 [ 2.32670746  0.40105202  0.73949329  0.13097136  0.72705166 -0.36497068]]


In [ ]:
print(X_train)

[[-0.14360052 -0.46037161 -0.47720996 -0.48380773  0.72705166  0.83012938]
 [-0.99276889  2.98532288  1.95619654 -0.48323058 -1.37541808  0.83012938]
 [ 0.01079373  0.40105202 -0.47720996 -0.32165051  0.72705166  0.83012938]
 ...
 [-0.01236541 -0.46037161 -0.47720996 -0.48701956  0.72705166  0.83012938]
 [ 0.47397648  0.40105202 -0.47720996 -0.29595582 -1.37541808  0.83012938]
 [ 2.32670746  0.40105202  0.73949329  0.13097136  0.72705166 -0.36497068]]


In [ ]:
print(X_test)

[[-0.01236541 -0.46037161 -0.47720996 -0.35409895  0.72705166  0.83012938]
 [-0.01236541 -0.46037161 -0.47720996 -0.49064251  0.72705166  0.83012938]
 [-1.76474013  2.98532288  0.73949329 -0.06420947  0.72705166  0.83012938]
 ...
 [-0.83837464 -0.46037161 -0.47720996 -0.48619536  0.72705166  0.83012938]
 [-0.68398039  1.26247564  1.95619654  4.54601107 -1.37541808 -1.56007074]
 [-1.9963315   0.40105202  0.73949329 -0.30979142 -1.37541808  0.83012938]]


In [ ]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
classifier =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[119  20]
 [ 26  58]]


In [ ]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 79.37


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives)
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.3f' % (precision*100))

Precision: 74.359


In [ ]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))

Recall: 69.048


In [ ]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# calculate score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

F-Measure: 71.605


In [ ]:
Age= 30     
SibSp=1
Parch=1    
Fare= 100   
Sex= 1     
Pclass=3    

output=classifier.predict(sc.transform([[Age ,SibSp,Parch,Fare, Sex, Pclass]]))
print("Passenger will die =", output)
if output==[1]:
  print( 'Passanger will survive')
else:
  print('Passanger will die')


Passenger will die = [0]
Passanger will die


In [ ]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/Knearestneighborclassifier.pkl', 'wb')) 
# Saving model to disk
 

[INFO] Saving model...


In [ ]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/Knearestneighborclassifier.pkl', 'rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1])

In [ ]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/finalized_model_KNN.sav'
joblib.dump(classifier, filename)
 
# some time later...
 
# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.7937219730941704


In [ ]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[112  27]
 [ 22  62]]


In [ ]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy Naive Bayes: %.2f' % (accuracy_score(y_test, y_pred)*100))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives)
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.3f' % (precision*100))

# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))

# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# calculate score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))


Accuracy Naive Bayes: 78.03
Precision: 69.663
Recall: 73.810
F-Measure: 71.676


In [ ]:
Age= 30     
SibSp=1
Parch=1    
Fare= 100   
Sex= 1     
Pclass=3    

output=classifier.predict(sc.transform([[Age ,SibSp,Parch,Fare, Sex, Pclass]]))
print("Passenger will die =", output)
if output==[1]:
  print( 'Passanger will survive')
else:
  print('Passanger will die')

Passenger will die = [0]
Passanger will die


In [ ]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/naivebayesclassifier.pkl', 'wb')) 
# Saving model to disk

[INFO] Saving model...


In [ ]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/naivebayesclassifier.pkl', 'rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1])

In [ ]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/finalized_model_NaiveBayes.sav'
joblib.dump(classifier, filename)
 
# some time later...
 
# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print("Naive Bayes", result)

Naive Bayes 0.7802690582959642


In [ ]:
!pip install streamlit


In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install pyngrok

     |████████████████████████████████| 747kB 16.1MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.0.5-cp37-none-any.whl size=19246 sha256=a0b9ec88ba6a77106609281e13ef9b71b70f8aa1ac51ae17582bde9119cf320d
  Stored in directory: /root/.cache/pip/wheels/0c/13/64/5ebbcc22eaf53fdf5766b397c1fb17c83f5775fdccf0ea1b88
Successfully built pyngrok


In [ ]:
!ngrok authtoken 1rQ8XkYyUBK9R8KvW6wdVZD6HNI_44Zoypk4KP8df9VdpBAuQ


Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
model = pickle.load(open('/content/drive/My Drive/Knearestneighborclassifier.pkl', 'rb'))
model_naive = pickle.load(open('/content/drive/My Drive/naivebayesclassifier.pkl', 'rb'))
dataset= pd.read_csv('/content/drive/My Drive/titanic.csv')
X=dataset[["Age","SibSp","Parch","Fare","Sex","Pclass"]]

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X["Sex"] = labelencoder_X.fit_transform(X["Sex"])

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
def predict_note_authentication(Age,SibSp,Parch,Sex,Fare,Pclass):
 output= model.predict(sc.transform([[Age,SibSp,Parch,Sex,Fare,Pclass]]))
 print("Passenger will die =", output)
 if output==[1]:
  prediction="Passanger will survive"
 else:
  prediction="Passanger will die"
 print(prediction)
 return prediction

def predict_naive(Age,SibSp,Parch,Fare,Sex,Pclass):
 output= model_naive.predict(sc.transform([[Age,SibSp,Parch,Fare,Sex,Pclass]]))
 print("Passenger will die =", output)
 if output==[1]:
   prediction="Passanger will survive"
 else:
   prediction="Passanger will die"
 print(prediction)
 return prediction
def main():
    
    html_temp = """
   <div class="" style="background-color:blue;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:white;margin-top:10px;"Machine Learning Lab Experiment</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    st.header("Passenger Will Survive Or Not Prediction using K nearest neighbor And Naive Bayes")
    
  
    Sex = st.number_input('Insert sex')
    Age = st.number_input('Insert a Age',18,60)
    SibSp = st.number_input('Insert a SibSp',0,10)
    Parch = st.number_input('Insert a Parch',1,10)
    Pclass = st.number_input('Insert a Pclass',18,60)
   
    Fare = st.number_input("Insert Fare",1,15000)
    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(Age,SibSp,Parch,Fare,Sex,Pclass)
      st.success('Model has predicted {}'.format(result))
    if st.button("Naive Bayes Predict"):
      result=predict_naive(Age,SibSp,Parch,Fare,Sex,Pclass)
      st.success('Model has predicted {}'.format(result))
      
    if st.button("About"):
      st.subheader("Developed by Satyam Sharma")
      st.subheader("Department of Computer Engineering")

if __name__=='__main__':
  main()

Overwriting app.py


In [ ]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [ ]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url

<NgrokTunnel: "http://d7021901aa07.ngrok.io" -> "http://localhost:80">

In [ ]:
!streamlit run --server.port 80 app.py

2021-04-22 10:28:24.858 An update to the [server] config option section was detected. To have these changes be reflected, please restart streamlit.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://34.86.207.27:80

/content/app.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex"] = labelencoder_X.fit_transform(X["Sex"])
  Stopping...


In [ ]:
ngrok.kill()